 ---
title: "Eike Analysis"
output: html_notebook
---

First loading all packages and data...


```{r}
library('openxlsx')
library('dplyr')
library('ggplot2')
library('reshape2')
data.path <- '../data/'

raw.data <- read.xlsx(paste0(data.path,'AVM_DSA_Update_EPIE_DBER.xlsx'),sheet = 1)

#kick out Nan columns
clean.data <- raw.data[,-c(1,2,3,4,5,8,9,10,11,12,13,19,22,30,33,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,69,76,77)]


```

Originially 77 variables only 48 remain, clean for nan. Now we plot the correlation matrix 

```{r, echo=TRUE}
write.csv(clean.data, file = paste0(data.path,'Clean_data.csv'))

```





```{r}
fit <- lm(`Volume.of.Hemorrhage..ml.` ~ ., data = filtered.data)
summary(fit)
```

```{r}
fit.one <- lm(`Volume.of.Hemorrhage..ml.` ~ `Report..Smaller...0.no..1.yes`, data = filtered.data)
summary(fit.one)

```

```{r}

library('ggplot2')
library('partykit')


ggplot(data = clean.data, aes(y = `Volume.of.Hemorrhage.(ml)`, x = `2nd.DSA.Venous.drainage;.0=superficial;.1=deep`)) + 
         geom_point() + 
          geom_smooth(method = lm)

clean.data.num <- sapply(clean.data,FUN = as.numeric)

clean.data.v2 <- as.data.frame(clean.data.num)


library('rpart')

fit.tree <- rpart(data = clean.data.v2, `Volume.of.Hemorrhage.(ml)` ~ .,  method = 'anova', control = rpart.control(cp = 0.003))

plot(as.party(fit.tree))

```
 Jetzt ne Anova fuer die Parameter: 


```{r}

library('reshape2')
library('ggplot2')


bla3 <- clean.data.v2[,c(10:16,21:24,27:29)]

bla4 <- melt(bla3)

tmp.1 <- c(rep('Nidus width',59),
           rep('Nidus height',59),
           rep('Nidus depth',59),
           rep('Nidus volume',59),
           rep('Venuous drainage',59),
           rep('Eloquence',59),
           rep('Martin Spetzler',59))

tmp.2 <- rep(tmp.1,2)

bla4$condition <- tmp.2

tmp.3 <- c(rep('1st',length(tmp.1)),
           rep('2nd',length(tmp.1)))

bla4$time <- tmp.3


names(bla4)[3:4] <- c('Condition','Time')


ggplot(data = bla4, aes(x= Condition, y = value, fill = Time)) + 
         geom_boxplot() + scale_y_continuous(limits = c(0,100))


#plot differences 

bla5 <- melt(bla3[,1:7] - bla3[,8:14])


bla5$Condition <- tmp.1


ggplot(data = bla5, aes(x= Condition, y = value)) + 
         geom_boxplot(fill='cornflowerblue') + scale_y_continuous(limits = c(-10,10))  +
         labs(title = 'Difference 1st and 2nd visit')

sol.t <- list()


for (idx in 1:7){

sol.t[[idx]] <- t.test(bla3[,idx],bla3[,idx + 8 - 1],paired = TRUE)


print(sol.t[[idx]])

}


```

```{r, echo=TRUE}
library('caret')
library('corrplot')
library('Hmisc')

new.data <- clean.data.v2

data.cor <- cor(new.data,use = 'complete.obs')
png('CorPlot.png', width = 2000, height = 2000)
corrplot(data.cor,method = 'circle')
dev.off()

#tmp <- findCorrelation(data.cor,cutoff = 0.8)

#filtered.data <- new.data[,-c(tmp)]

data.cor <- cor(filtered.data,use = 'complete.obs')
png('CorPlot_clean.png', width = 2000, height = 2000)
corrplot(data.cor,method = 'circle')
dev.off()

#now with probabilities
res <- rcorr(as.matrix(new.data))


flattenCorrMatrix <- function(cormat, pmat) {
  ut <- upper.tri(cormat)
  data.frame(
    row = rownames(cormat)[row(cormat)[ut]],
    column = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut],
    p = pmat[ut]
    )
}

cortable <- flattenCorrMatrix(res$r,res$P)

corrtable <- data.frame(cortable$row[948:990],round(cortable$cor[948:990],2),round(cortable$p[948:990],3))

names(corrtable) <- c('Parameter','Correlation','p value')


write.xlsx(corrtable, "Corrtable_VolumeOfHemorrhage.xlsx")

```

```{r}
library('car')

#only keep Volumen of Hemorrhage, Venuous Stenosis and Report Smaller Yes/No

scatterplotMatrix(~ `Volume.of.Hemorrhage.(ml)` + `venous.stenosis.(70%);.0=No;.1=yes` + `Report:.Smaller?;.0=no;.1=yes`, data = new.data)
      


```

